baseURL = 'https://example.org/'
languageCode = 'zh-cn'
title = 'qiusheng2011'
theme='hugo-xmin-master'

[[menus.main]]
name = '我的简历'
pageRef = '/resume/'
weight = 10

[module]
  [module.hugoVersion]
    extended = false
    min = "0.116.0"