baseURL = 'https://example.org/'
languageCode = 'zh-cn'
title = 'qiusheng2011'
theme='hugo-xmin-master'
publishDir="qiusheng2011_resume.github.io"
relativeURLs=true

[[menus.main]]
name = '项目'
pageRef = '/project'
weight = 10

[module]
  [module.hugoVersion]
    extended = false
    min = "0.116.0"